#include "doctest.h"

#include "../include/album.h"
#include "../include/artista.h"
#include "../include/banco_usuarios.h"
#include "../include/biblioteca.h"
#include "../include/conjunto_listas.h"
#include "../include/discografia.h"
#include "../include/lista_musica.h"
#include "../include/musica.h"
#include "../include/playlist.h"
#include "../include/recomendacao.h"
#include "../include/sistema.h"
#include "../include/usuario.h"